
name: sync tinymta to tinymta_com
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: sync tinymta.us.to to tinymta.com
        run: |
            git clone -b master "https://github.com/bulk88/tinymta.git"
            cd tinymta
            git remote add mirror-remote "https://${{secrets.TINYMTACOM_PAT}}@github.com/bulk88/tinymta_com.git"
            sed -i 's/tinymta\.us\.to/tinymta.com/g' ./docs/CNAME
            git -c user.name="Your Name" -c user.email="you@example.com" commit -a -m "change CNAME domain (bot)"
            git push -v --progress --force --all mirror-remote 
