
name: sync tinymta to tinymta_com
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: sync tinymta.us.to to tinymta.com
        run: |
            git clone -n --filter=tree:0 "https://github.com/bulk88/tinymta.git"
            cd tinymta
            git remote add -f mirror-remote "https://${{secrets.TINYMTACOM_PAT}}@github.com/bulk88/tinymta_com.git"
            git checkout master docs/CNAME ;     git checkout master docs/CNAME
            sed -i 's/tinymta\.us\.to/tinymta.com/g' ./docs/CNAME
            git add ./docs/CNAME
            git -c user.name="Domain Change Bot" -c user.email="no-reply@no-reply.com" commit -o ./docs/CNAME -m "change CNAME domain (bot)"
            git push --progress --force --all mirror-remote
